---
- hosts: localhost
  become_method: sudo
  remote_user: root
  connection: local
  gather_facts: false
  vars_files:
    - vars/main.yml
  roles:
    - ec2_role
    - refresh

- hosts: tag_Name_{{ ec2_config.instance_tag_name1 }}
  become_method: sudo
  remote_user: root
  gather_facts: false
  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: 'install python2'
      raw: yum install -y python
- hosts: tag_Name_{{ ec2_config.instance_tag_name1 }}
  become_method: sudo
  remote_user: root
  gather_facts: true
  vars_files:
    - vars/main.yml
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
#    - role: devops.tomcat7
    - role: geerlingguy.mysql
    - role: geerlingguy.jenkins
#  tasks:
#  - template:
#      src: /root/ragini/sensu-dynamic/ragini/user_xml.j2
#      dest: /usr/share/tomcat/conf/tomcat-users.xml
#  - systemd:
#      name: tomcat
#      state: started

  tasks:
    - name: installing pip
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /root
    - name: installing pip
      shell: sudo python get-pip.py

    - name: Install the Python MySQLB module
      pip: name=MySQL-python state=latest

    - name: Create the flask database
      mysql_db: name=rag_db state=present

   
    

- include: sensu_master.yml

